adjective1 = input("Enter an adjective (description): ")
adjective2 = input("Enter an adjective (description): ")
adjective3 = input("Enter an adjective (description): ")
noun1 = input("Enter a noun (animal, person, place, thing): ")
verb1 = input("Enter a verb ending with 'ing': ")

print(f"Today I Went to a {adjective1} zoo.")
print(f"In an exhibit, I saw a {noun1}")
print(f"{noun1} was {adjective2} and {verb1}")
print(f"I was {adjective3}!")